CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(200) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    SenhaHash NVARCHAR(300) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IX_Users_Email ON Users(Email);
